name: Build

on: 
  push:
    branches:
      - "**"
    tags-ignore:
      - 'v*'
  pull_request: {}
      

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'zhangyuan/sqlparser'
    steps:
    - uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: Build release binary
      run: cargo build --release && du -sh target/release/aws-auth
    - name: Strip release binary
      run: strip target/release/aws-auth && du -sh target/release/aws-auth
    - name: Compress binary
      uses: svenstaro/upx-action@v2
      with:
        file: target/release/aws-auth
